sudo: required 
services:
  - docker
before_install:
  - docker build -t vallabh1421/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run vallabh1421/react-test npm test 

after_success:
  - docker build -t vallabh1421/multi-client ./client
  - docker build -t vallabh1421/multi-nginx ./nginx
  - docker build -t vallabh1421/multi-server ./server
  - docker build -t vallabh1421/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push vallabh1421/multi-client
  - docker push vallabh1421/multi-nginx
  - docker push vallabh1421/multi-server
  - docker push vallabh1421/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-1234567890"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY